import { BlogPost, Cart, Category, Order, Product, ShopLook, User } from '@/core/models';

const now = '2026-03-13T00:00:00.000Z';

const MOCK_GROUPS = {
  tabletop: { id: 1, name: 'Bàn ăn & Bếp', slug: 'ban-an-bep', isActive: true, displayOrder: 1 },
  decor: { id: 2, name: 'Trang trí & Sắp đặt', slug: 'trang-tri-sap-dat', isActive: true, displayOrder: 2 },
  lighting: { id: 3, name: 'Ánh sáng & Hương thơm', slug: 'anh-sang-huong-thom', isActive: true, displayOrder: 3 }
} as const;

export const MOCK_CATEGORIES: Category[] = [
  { id: 1, slug: 'phu-kien-ban', name: 'Phụ kiện bàn', isActive: true, group: { ...MOCK_GROUPS.tabletop } },
  { id: 2, slug: 'lighting', name: 'Lighting', isActive: true, group: { ...MOCK_GROUPS.lighting } },
  { id: 3, slug: 'decor', name: 'Decor', isActive: true, group: { ...MOCK_GROUPS.decor } },
  { id: 4, slug: 'furniture', name: 'Furniture', isActive: true, group: { ...MOCK_GROUPS.decor } },
  { id: 5, slug: 'textile', name: 'Textile', isActive: true, group: { ...MOCK_GROUPS.decor } },
  { id: 6, slug: 'kitchen', name: 'Kitchen', isActive: true, group: { ...MOCK_GROUPS.tabletop } }
];

export const MOCK_CATEGORY_PRODUCTS: Product[] = [
  {
    id: 101,
    sku: 'BEE-101',
    slug: 'khay-cam-but-go-soi',
    name: 'Khay Cắm Bút Gỗ Sồi',
    price: 150000,
    originalPrice: 180000,
    categoryId: 1,
    category: 'Phụ kiện bàn',
    image: 'https://picsum.photos/id/101/400/500',
    hoverImage: 'https://picsum.photos/id/102/400/500',
    tag: 'NEW',
    rating: 4.8,
    reviews: 45,
    color: '#8B4513',
    material: 'Gỗ',
    style: 'Minimalist',
    isActive: true,
    createdAt: now
  },
  {
    id: 102,
    sku: 'BEE-102',
    slug: 'den-ban-pixar',
    name: 'Đèn Bàn Pixar',
    price: 350000,
    categoryId: 2,
    category: 'Lighting',
    image: 'https://picsum.photos/id/103/400/500',
    hoverImage: 'https://picsum.photos/id/104/400/500',
    tag: '-20%',
    rating: 4.9,
    reviews: 120,
    color: '#333333',
    material: 'Kim loại',
    style: 'Hiện đại',
    isActive: true,
    createdAt: now
  },
  {
    id: 103,
    sku: 'BEE-103',
    slug: 'bang-ghim-ghi-chu',
    name: 'Bảng Ghim Ghi Chú',
    price: 120000,
    categoryId: 1,
    category: 'Phụ kiện bàn',
    image: 'https://picsum.photos/id/106/400/500',
    hoverImage: 'https://picsum.photos/id/107/400/500',
    rating: 4.5,
    reviews: 30,
    color: '#D2B48C',
    material: 'Vải',
    style: 'Vintage',
    isActive: true,
    createdAt: now
  },
  {
    id: 104,
    sku: 'BEE-104',
    slug: 'chau-cay-mini-de-ban',
    name: 'Chậu Cây Mini Để Bàn',
    price: 85000,
    categoryId: 3,
    category: 'Decor',
    image: 'https://picsum.photos/id/112/400/500',
    hoverImage: 'https://picsum.photos/id/113/400/500',
    tag: 'Best Seller',
    rating: 5,
    reviews: 210,
    color: '#4CAF50',
    material: 'Gốm sứ',
    style: 'Dễ thương',
    isActive: true,
    createdAt: now
  },
  {
    id: 105,
    sku: 'BEE-105',
    slug: 'lich-go-de-ban',
    name: 'Lịch Gỗ Để Bàn',
    price: 190000,
    categoryId: 1,
    category: 'Phụ kiện bàn',
    image: 'https://picsum.photos/id/133/400/500',
    hoverImage: 'https://picsum.photos/id/134/400/500',
    rating: 4.7,
    reviews: 15,
    color: '#8B4513',
    material: 'Gỗ',
    style: 'Minimalist',
    isActive: true,
    createdAt: now
  },
  {
    id: 106,
    sku: 'BEE-106',
    slug: 'coc-gom-handmade',
    name: 'Cốc Gốm Handmade',
    price: 145000,
    originalPrice: 160000,
    categoryId: 3,
    category: 'Decor',
    image: 'https://picsum.photos/id/145/400/500',
    hoverImage: 'https://picsum.photos/id/146/400/500',
    rating: 4.6,
    reviews: 55,
    color: '#FFFFFF',
    material: 'Gốm sứ',
    style: 'Vintage',
    isActive: true,
    createdAt: now
  },
  {
    id: 107,
    sku: 'BEE-107',
    slug: 'dong-ho-lat-so',
    name: 'Đồng Hồ Lật Số',
    price: 450000,
    categoryId: 3,
    category: 'Decor',
    image: 'https://picsum.photos/id/175/400/500',
    hoverImage: 'https://picsum.photos/id/176/400/500',
    tag: 'Sold Out',
    rating: 4.9,
    reviews: 80,
    color: '#333333',
    material: 'Nhựa',
    style: 'Hiện đại',
    isActive: true,
    createdAt: now
  },
  {
    id: 108,
    sku: 'BEE-108',
    slug: 'tham-chuot-da',
    name: 'Thảm Chuột Da',
    price: 220000,
    categoryId: 1,
    category: 'Phụ kiện bàn',
    image: 'https://picsum.photos/id/160/400/500',
    hoverImage: 'https://picsum.photos/id/161/400/500',
    rating: 4.8,
    reviews: 90,
    color: '#8B4513',
    material: 'Da',
    style: 'Minimalist',
    brand: 'Nordic Nest',
    inStock: true,
    isActive: true,
    createdAt: now
  },
  {
    id: 109,
    sku: 'BEE-109',
    slug: 'bo-khay-go-trang-tri-ban-an',
    name: 'Bộ Khay Gỗ Trang Trí Bàn Ăn',
    price: 520000,
    originalPrice: 690000,
    categoryId: 6,
    category: 'Kitchen',
    image: 'https://picsum.photos/id/140/400/500',
    hoverImage: 'https://picsum.photos/id/141/400/500',
    rating: 4.6,
    reviews: 66,
    color: '#B08968',
    material: 'Gỗ',
    style: 'Vintage',
    brand: 'Moc Decor',
    inStock: true,
    isActive: true,
    createdAt: now
  },
  {
    id: 110,
    sku: 'BEE-110',
    slug: 'den-tha-tran-cafe-loft',
    name: 'Đèn Thả Trần Cafe Loft',
    price: 890000,
    categoryId: 2,
    category: 'Lighting',
    image: 'https://picsum.photos/id/321/400/500',
    hoverImage: 'https://picsum.photos/id/322/400/500',
    tag: 'Best Seller',
    rating: 4.9,
    reviews: 143,
    color: '#222222',
    material: 'Kim loại',
    style: 'Hiện đại',
    brand: 'LumiHome',
    inStock: true,
    isActive: true,
    createdAt: now
  },
  {
    id: 111,
    sku: 'BEE-111',
    slug: 'goi-tua-sofa-boho',
    name: 'Gối Tựa Sofa Boho',
    price: 180000,
    originalPrice: 240000,
    categoryId: 5,
    category: 'Textile',
    image: 'https://picsum.photos/id/325/400/500',
    hoverImage: 'https://picsum.photos/id/326/400/500',
    rating: 4.4,
    reviews: 38,
    color: '#E0A96D',
    material: 'Vải',
    style: 'Dễ thương',
    brand: 'SoftNest',
    inStock: true,
    isActive: true,
    createdAt: now
  },
  {
    id: 112,
    sku: 'BEE-112',
    slug: 'ke-go-treo-tuong-hex',
    name: 'Kệ Gỗ Treo Tường Hex',
    price: 430000,
    categoryId: 3,
    category: 'Decor',
    image: 'https://picsum.photos/id/330/400/500',
    hoverImage: 'https://picsum.photos/id/331/400/500',
    rating: 4.7,
    reviews: 57,
    color: '#7F5539',
    material: 'Gỗ',
    style: 'Minimalist',
    brand: 'BeeLiving',
    inStock: false,
    isActive: true,
    createdAt: now
  },
  {
    id: 113,
    sku: 'BEE-113',
    slug: 'tham-lua-trang-tri-phong-ngu',
    name: 'Thảm Lụa Trang Trí Phòng Ngủ',
    price: 760000,
    originalPrice: 960000,
    categoryId: 5,
    category: 'Textile',
    image: 'https://picsum.photos/id/338/400/500',
    hoverImage: 'https://picsum.photos/id/339/400/500',
    rating: 4.9,
    reviews: 102,
    color: '#C9ADA7',
    material: 'Vải',
    style: 'Hiện đại',
    brand: 'SoftNest',
    inStock: true,
    isActive: true,
    createdAt: now
  },
  {
    id: 114,
    sku: 'BEE-114',
    slug: 'set-thia-nia-go-6-mon',
    name: 'Set Thìa Nĩa Gỗ 6 Món',
    price: 250000,
    categoryId: 6,
    category: 'Kitchen',
    image: 'https://picsum.photos/id/344/400/500',
    hoverImage: 'https://picsum.photos/id/345/400/500',
    rating: 4.3,
    reviews: 22,
    color: '#A47148',
    material: 'Gỗ',
    style: 'Vintage',
    brand: 'Moc Decor',
    inStock: true,
    isActive: true,
    createdAt: now
  },
  {
    id: 115,
    sku: 'BEE-115',
    slug: 'den-ngu-go-co-dimmer',
    name: 'Đèn Ngủ Gỗ Có Dimmer',
    price: 680000,
    categoryId: 2,
    category: 'Lighting',
    image: 'https://picsum.photos/id/350/400/500',
    hoverImage: 'https://picsum.photos/id/351/400/500',
    tag: 'NEW',
    rating: 4.8,
    reviews: 41,
    color: '#2D2D2D',
    material: 'Gỗ',
    style: 'Minimalist',
    brand: 'LumiHome',
    inStock: true,
    isActive: true,
    createdAt: now
  },
  {
    id: 116,
    sku: 'BEE-116',
    slug: 'tu-dau-giuong-2-ngan-keo',
    name: 'Tủ Đầu Giường 2 Ngăn Kéo',
    price: 1490000,
    categoryId: 4,
    category: 'Furniture',
    image: 'https://picsum.photos/id/355/400/500',
    hoverImage: 'https://picsum.photos/id/356/400/500',
    rating: 4.6,
    reviews: 29,
    color: '#8D6E63',
    material: 'Gỗ',
    style: 'Hiện đại',
    brand: 'Nordic Nest',
    inStock: true,
    isActive: true,
    createdAt: now
  },
  {
    id: 117,
    sku: 'BEE-117',
    slug: 'khan-trai-ban-linen-kem',
    name: 'Khăn Trải Bàn Linen Kem',
    price: 310000,
    originalPrice: 390000,
    categoryId: 6,
    category: 'Kitchen',
    image: 'https://picsum.photos/id/361/400/500',
    hoverImage: 'https://picsum.photos/id/362/400/500',
    rating: 4.5,
    reviews: 36,
    color: '#EDE0D4',
    material: 'Vải',
    style: 'Minimalist',
    brand: 'BeeLiving',
    inStock: false,
    isActive: true,
    createdAt: now
  },
  {
    id: 118,
    sku: 'BEE-118',
    slug: 'bo-3-khung-tranh-truu-tuong',
    name: 'Bộ 3 Khung Tranh Trừu Tượng',
    price: 580000,
    categoryId: 3,
    category: 'Decor',
    image: 'https://picsum.photos/id/368/400/500',
    hoverImage: 'https://picsum.photos/id/369/400/500',
    rating: 4.7,
    reviews: 73,
    color: '#B0A8B9',
    material: 'Canvas',
    style: 'Hiện đại',
    brand: 'Artify',
    inStock: true,
    isActive: true,
    createdAt: now
  },
  {
    id: 119,
    sku: 'BEE-119',
    slug: 'nen-thom-vani-hu-thuy-tinh',
    name: 'Nến Thơm Vani Hũ Thủy Tinh',
    price: 165000,
    originalPrice: 210000,
    categoryId: 3,
    category: 'Decor',
    image: 'https://picsum.photos/id/375/400/500',
    hoverImage: 'https://picsum.photos/id/376/400/500',
    rating: 4.2,
    reviews: 64,
    color: '#FFF4D6',
    material: 'Sáp đậu nành',
    style: 'Dễ thương',
    brand: 'AromaBee',
    inStock: true,
    isActive: true,
    createdAt: now
  },
  {
    id: 120,
    sku: 'BEE-120',
    slug: 'binh-hoa-thuy-tinh-xanh-rieu',
    name: 'Bình Hoa Thủy Tinh Xanh Rêu',
    price: 410000,
    categoryId: 3,
    category: 'Decor',
    image: 'https://picsum.photos/id/381/400/500',
    hoverImage: 'https://picsum.photos/id/382/400/500',
    rating: 4.8,
    reviews: 88,
    color: '#2A9D8F',
    material: 'Thủy tinh',
    style: 'Vintage',
    brand: 'Artify',
    inStock: true,
    isActive: true,
    createdAt: now
  },
  {
    id: 121,
    sku: 'BEE-121',
    slug: 'ghe-don-boc-vai-nhung',
    name: 'Ghế Đôn Bọc Vải Nhung',
    price: 980000,
    categoryId: 4,
    category: 'Furniture',
    image: 'https://picsum.photos/id/388/400/500',
    hoverImage: 'https://picsum.photos/id/389/400/500',
    rating: 4.5,
    reviews: 27,
    color: '#6D597A',
    material: 'Vải',
    style: 'Vintage',
    brand: 'Nordic Nest',
    inStock: true,
    isActive: true,
    createdAt: now
  },
  {
    id: 122,
    sku: 'BEE-122',
    slug: 'bo-ly-thuy-tinh-co-vien-vang',
    name: 'Bộ Ly Thủy Tinh Viền Vàng',
    price: 460000,
    originalPrice: 520000,
    categoryId: 6,
    category: 'Kitchen',
    image: 'https://picsum.photos/id/394/400/500',
    hoverImage: 'https://picsum.photos/id/395/400/500',
    rating: 4.9,
    reviews: 112,
    color: '#F4EBD0',
    material: 'Thủy tinh',
    style: 'Hiện đại',
    brand: 'Moc Decor',
    inStock: true,
    isActive: true,
    createdAt: now
  },
  {
    id: 123,
    sku: 'BEE-123',
    slug: 'guong-tron-vien-go-soi',
    name: 'Gương Tròn Viền Gỗ Sồi',
    price: 1250000,
    categoryId: 3,
    category: 'Decor',
    image: 'https://picsum.photos/id/401/400/500',
    hoverImage: 'https://picsum.photos/id/402/400/500',
    rating: 4.7,
    reviews: 46,
    color: '#D6CCC2',
    material: 'Gỗ',
    style: 'Minimalist',
    brand: 'BeeLiving',
    inStock: true,
    isActive: true,
    createdAt: now
  },
  {
    id: 124,
    sku: 'BEE-124',
    slug: 'set-khay-gom-breakfast',
    name: 'Set Khay Gốm Breakfast',
    price: 340000,
    categoryId: 6,
    category: 'Kitchen',
    image: 'https://picsum.photos/id/409/400/500',
    hoverImage: 'https://picsum.photos/id/410/400/500',
    rating: 4.3,
    reviews: 18,
    color: '#E3D5CA',
    material: 'Gốm sứ',
    style: 'Dễ thương',
    brand: 'AromaBee',
    inStock: false,
    isActive: true,
    createdAt: now
  }
];

export const MOCK_TRENDING_PRODUCTS: Product[] = [
  {
    id: 1,
    sku: 'BEE-001',
    slug: 'honeycomb-wall-shelf',
    name: 'Honeycomb Wall Shelf',
    price: 450000,
    categoryId: 3,
    category: 'Decor',
    image: 'https://picsum.photos/id/1011/400/500',
    hoverImage: 'https://picsum.photos/id/1012/400/500',
    tag: '-15%',
    style: 'Hiện đại',
    material: 'Gỗ',
    isActive: true,
    createdAt: now
  },
  {
    id: 2,
    sku: 'BEE-002',
    slug: 'amber-glass-vase',
    name: 'Amber Glass Vase',
    price: 280000,
    categoryId: 3,
    category: 'Decor',
    image: 'https://picsum.photos/id/1082/400/500',
    hoverImage: 'https://picsum.photos/id/1080/400/500',
    tag: 'Best Seller',
    style: 'Vintage',
    material: 'Thủy tinh',
    isActive: true,
    createdAt: now
  },
  {
    id: 3,
    sku: 'BEE-003',
    slug: 'velvet-mustard-cushion',
    name: 'Velvet Mustard Cushion',
    price: 150000,
    categoryId: 5,
    category: 'Textile',
    image: 'https://picsum.photos/id/1069/400/500',
    hoverImage: 'https://picsum.photos/id/1070/400/500',
    style: 'Dễ thương',
    material: 'Vải',
    isActive: true,
    createdAt: now
  },
  {
    id: 4,
    sku: 'BEE-004',
    slug: 'minimalist-desk-lamp',
    name: 'Minimalist Desk Lamp',
    price: 620000,
    categoryId: 2,
    category: 'Lighting',
    image: 'https://picsum.photos/id/1033/400/500',
    hoverImage: 'https://picsum.photos/id/1040/400/500',
    tag: 'NEW',
    style: 'Minimalist',
    material: 'Kim loại',
    isActive: true,
    createdAt: now
  }
];

export const MOCK_FLASH_SALE_PRODUCTS: Product[] = [
  {
    id: 5,
    sku: 'BEE-005',
    slug: 'scented-soy-candle',
    name: 'Scented Soy Candle',
    price: 120000,
    originalPrice: 200000,
    categoryId: 3,
    category: 'Decor',
    image: 'https://picsum.photos/id/106/300/300',
    hoverImage: 'https://picsum.photos/id/106/300/300',
    soldPercentage: 85,
    stockLeft: 12,
    style: 'Dễ thương',
    isActive: true,
    createdAt: now
  },
  {
    id: 6,
    sku: 'BEE-006',
    slug: 'ceramic-plant-pot',
    name: 'Ceramic Plant Pot',
    price: 89000,
    originalPrice: 150000,
    categoryId: 3,
    category: 'Decor',
    image: 'https://picsum.photos/id/112/300/300',
    hoverImage: 'https://picsum.photos/id/113/300/300',
    soldPercentage: 60,
    stockLeft: 40,
    style: 'Minimalist',
    material: 'Gốm sứ',
    isActive: true,
    createdAt: now
  },
  {
    id: 7,
    sku: 'BEE-007',
    slug: 'macrame-wall-hanging',
    name: 'Macrame Wall Hanging',
    price: 250000,
    originalPrice: 350000,
    categoryId: 3,
    category: 'Decor',
    image: 'https://picsum.photos/id/114/300/300',
    hoverImage: 'https://picsum.photos/id/115/300/300',
    soldPercentage: 92,
    stockLeft: 5,
    style: 'Vintage',
    material: 'Vải',
    isActive: true,
    createdAt: now
  },
  {
    id: 8,
    sku: 'BEE-008',
    slug: 'rattan-basket-set',
    name: 'Rattan Basket Set',
    price: 320000,
    originalPrice: 450000,
    categoryId: 3,
    category: 'Decor',
    image: 'https://picsum.photos/id/116/300/300',
    hoverImage: 'https://picsum.photos/id/117/300/300',
    soldPercentage: 45,
    stockLeft: 55,
    style: 'Vintage',
    material: 'Gỗ',
    isActive: true,
    createdAt: now
  }
];

export const MOCK_NEW_COLLECTION_PRODUCTS: Product[] = [
  {
    id: 501,
    sku: 'BEE-501',
    slug: 'lo-hoa-gom-moc',
    name: 'Lọ Hoa Gốm Mộc',
    price: 280000,
    categoryId: 3,
    category: 'Decor',
    image: 'https://picsum.photos/id/113/500/600',
    hoverImage: 'https://picsum.photos/id/114/500/600',
    videoUrl: 'https://videos.pexels.com/video-files/4057322/4057322-uhd_2560_1440_25fps.mp4',
    tag: 'NEW',
    rating: 5,
    reviews: 12,
    style: 'Vintage',
    material: 'Gốm sứ',
    isActive: true,
    createdAt: now
  },
  {
    id: 502,
    sku: 'BEE-502',
    slug: 'den-ngu-chan-go',
    name: 'Đèn Ngủ Chân Gỗ',
    price: 550000,
    categoryId: 2,
    category: 'Lighting',
    image: 'https://picsum.photos/id/112/500/600',
    hoverImage: 'https://picsum.photos/id/111/500/600',
    videoUrl: 'https://videos.pexels.com/video-files/6981410/6981410-uhd_2560_1440_25fps.mp4',
    tag: 'NEW',
    rating: 4.8,
    reviews: 8,
    style: 'Minimalist',
    material: 'Gỗ',
    isActive: true,
    createdAt: now
  },
  {
    id: 503,
    sku: 'BEE-503',
    slug: 'bo-ga-goi-linen',
    name: 'Bộ Ga Gối Linen',
    price: 1250000,
    categoryId: 5,
    category: 'Textile',
    image: 'https://picsum.photos/id/102/500/600',
    hoverImage: 'https://picsum.photos/id/103/500/600',
    tag: 'NEW',
    rating: 4.9,
    reviews: 24,
    style: 'Hiện đại',
    material: 'Vải',
    isActive: true,
    createdAt: now
  },
  {
    id: 504,
    sku: 'BEE-504',
    slug: 'ghe-may-thu-gian',
    name: 'Ghế Mây Thư Giãn',
    price: 1800000,
    categoryId: 4,
    category: 'Furniture',
    image: 'https://picsum.photos/id/116/500/600',
    hoverImage: 'https://picsum.photos/id/117/500/600',
    tag: 'NEW',
    rating: 5,
    reviews: 5,
    style: 'Vintage',
    material: 'Gỗ',
    isActive: true,
    createdAt: now
  }
];

export const MOCK_NEW_ARRIVALS_PRODUCTS: Product[] = [
  {
    id: 9,
    sku: 'BEE-009',
    slug: 'abstract-art-print',
    name: 'Abstract Art Print',
    price: 180000,
    categoryId: 3,
    category: 'Decor',
    image: 'https://picsum.photos/id/201/300/400',
    hoverImage: 'https://picsum.photos/id/202/300/400',
    tag: 'NEW',
    style: 'Hiện đại',
    isActive: true,
    createdAt: now
  },
  {
    id: 10,
    sku: 'BEE-010',
    slug: 'linen-table-runner',
    name: 'Linen Table Runner',
    price: 220000,
    categoryId: 6,
    category: 'Kitchen',
    image: 'https://picsum.photos/id/203/300/400',
    hoverImage: 'https://picsum.photos/id/204/300/400',
    tag: 'NEW',
    style: 'Vintage',
    material: 'Vải',
    isActive: true,
    createdAt: now
  },
  {
    id: 11,
    sku: 'BEE-011',
    slug: 'wooden-serving-tray',
    name: 'Wooden Serving Tray',
    price: 350000,
    categoryId: 6,
    category: 'Kitchen',
    image: 'https://picsum.photos/id/206/300/400',
    hoverImage: 'https://picsum.photos/id/208/300/400',
    tag: 'NEW',
    style: 'Minimalist',
    material: 'Gỗ',
    isActive: true,
    createdAt: now
  },
  {
    id: 12,
    sku: 'BEE-012',
    slug: 'modern-wall-clock',
    name: 'Modern Wall Clock',
    price: 490000,
    categoryId: 3,
    category: 'Decor',
    image: 'https://picsum.photos/id/211/300/400',
    hoverImage: 'https://picsum.photos/id/212/300/400',
    tag: 'NEW',
    style: 'Hiện đại',
    material: 'Nhựa',
    isActive: true,
    createdAt: now
  }
];

export const MOCK_LOOKBOOK_ITEMS: ShopLook[] = [
  {
    id: 10,
    name: 'Góc Đọc Sách Yên Tĩnh',
    description: 'Sự kết hợp giữa ánh sáng vàng ấm và chất liệu gỗ sồi tự nhiên.',
    image: 'https://picsum.photos/id/1078/800/1000',
    hotspots: [
      {
        id: 901,
        x: 40,
        y: 60,
        product: {
          id: 502,
          sku: 'BEE-502',
          slug: 'den-ngu-chan-go',
          name: 'Đèn Ngủ Chân Gỗ',
          price: 550000,
          categoryId: 2,
          category: 'Lighting',
          image: 'https://picsum.photos/id/112/150/150',
          hoverImage: 'https://picsum.photos/id/112/150/150',
          isActive: true,
          createdAt: now
        }
      },
      {
        id: 902,
        x: 70,
        y: 80,
        product: {
          id: 504,
          sku: 'BEE-504',
          slug: 'ghe-may-thu-gian',
          name: 'Ghế Mây Thư Giãn',
          price: 1800000,
          categoryId: 4,
          category: 'Furniture',
          image: 'https://picsum.photos/id/116/150/150',
          hoverImage: 'https://picsum.photos/id/116/150/150',
          isActive: true,
          createdAt: now
        }
      }
    ]
  }
];

export const MOCK_SHOP_LOOKS: ShopLook[] = [
  {
    id: 1,
    name: 'Góc Làm Việc Tối Giản',
    description: 'Bàn học chỉ có bàn - hãy thêm các vật dụng decor của bạn.',
    image: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?q=80&w=2000&auto=format&fit=crop',
    hotspots: [
      {
        id: 101,
        x: 40,
        y: 20,
        product: {
          id: 92,
          sku: 'BEE-092',
          slug: 'tranh-minimalist',
          name: 'TRANH CANVAS MINIMAL',
          price: 150000,
          categoryId: 12,
          category: 'Trang trí tường',
          image: 'assets/images/tranh-canvas-minimal.jpg',
          hoverImage: 'assets/images/tranh-canvas-minimal.jpg',
          isActive: true,
          createdAt: now
        }
      },
      {
        id: 102,
        x: 20,
        y: 50,
        product: {
          id: 102,
          sku: 'BEE-102',
          slug: 'den-ban-pixar',
          name: 'ĐÈN BÀN PIXAR',
          price: 350000,
          categoryId: 2,
          category: 'Lighting',
          image: 'assets/images/den-ban.jpg',
          hoverImage: 'assets/images/den-ban.jpg',
          isActive: true,
          createdAt: now
        }
      },
      {
        id: 103,
        x: 60,
        y: 60,
        product: {
          id: 60,
          sku: 'BEE-060',
          slug: 'ly-sứ-minimal',
          name: 'LY SỨ MINIMAL',
          price: 60000,
          categoryId: 2,
          category: 'Cốc ly',
          image: 'assets/images/ly-minimal.jpg',
          hoverImage: 'assets/images/ly-minimal.jpg',
          isActive: true,
          createdAt: now
        }
      }
    ]
  },
  {
    id: 2,
    name: 'Phòng Ngủ Ấm Cúng',
    description: 'Không gian thư giãn sau một ngày làm việc mệt mỏi.',
    image: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?q=80&w=2070&auto=format&fit=crop',
    hotspots: [
      {
        id: 201,
        x: 45,
        y: 35,
        product: {
          id: 97,
          sku: 'BEE-097',
          slug: 'tranh-phòng-ngủ',
          name: 'TRANH PHÒNG NGỦ',
          price: 210000,
          categoryId: 12,
          category: 'Trang trí tường',
          image: 'assets/images/tranh-phong-ngu.jpg',
          hoverImage: 'assets/images/tranh-phong-ngu.jpg',
          isActive: true,
          createdAt: now
        }
      },
      {
        id: 202,
        x: 70,
        y: 55,
        product: {
          id: 73,
          sku: 'BEE-073',
          slug: 'nến-lavender-relax',
          name: 'NẾN LAVENDER RELAX',
          price: 120000,
          categoryId: 3,
          category: 'Hương thơm',
          image: 'assets/images/nen-thom-lavender-relax.jpg',
          hoverImage: 'assets/images/nen-thom-lavender-relax.jpg',
          isActive: true,
          createdAt: now
        }
      },
      {
        id: 203,
        x: 40,
        y: 80,
        product: {
          id: 82,
          sku: 'BEE-082',
          slug: 'thảm-lông-cao-cấp',
          name: 'THẢM LÔNG CAO CẤP',
          price: 250000,
          categoryId: 8,
          category: 'Phụ kiện vải',
          image: 'assets/images/tham-long.jpg',
          hoverImage: 'assets/images/tham-long.jpg',
          isActive: true,
          createdAt: now
        }
      }
    ]
  }
];

export const MOCK_BLOG_POSTS: BlogPost[] = [
  {
    id: 1,
    title: '5 cách setup góc làm việc tối giản',
    date: '2024-05-15',
    image: 'https://picsum.photos/id/301/600/400',
    summary: 'Biến góc làm việc trở nên gọn gàng và đầy cảm hứng với những mẹo nhỏ...'
  },
  {
    id: 2,
    title: 'Chọn nến thơm theo mùa',
    date: '2024-05-10',
    image: 'https://picsum.photos/id/302/600/400',
    summary: 'Mỗi mùa một hương thơm, cùng BeeShop khám phá những note hương...'
  },
  {
    id: 3,
    title: 'Xu hướng decor phòng ngủ 2024',
    date: '2024-05-01',
    image: 'https://picsum.photos/id/305/600/400',
    summary: 'Những tông màu ấm và chất liệu tự nhiên đang lên ngôi trong năm nay...'
  }
];

export const MOCK_INSTAGRAM_FEED: string[] = [
  'https://picsum.photos/id/55/300/300',
  'https://picsum.photos/id/56/300/300',
  'https://picsum.photos/id/57/300/300',
  'https://picsum.photos/id/58/300/300',
  'https://picsum.photos/id/59/300/300'
];

export const MOCK_USERS: User[] = [
  {
    id: 1,
    email: 'ngoc@beeshop.vn',
    fullName: 'Ngọc Nguyễn',
    phone: '0901000001',
    addresses: [
      {
        id: 1,
        fullName: 'Ngọc Nguyễn',
        phone: '0901000001',
        line1: '123 Tổ Ong',
        ward: 'Phường Bưởi',
        district: 'Tây Hồ',
        city: 'Hà Nội',
        isDefault: true
      }
    ],
    createdAt: now
  }
];

export const MOCK_CARTS: Cart[] = [
  {
    id: 1,
    userId: 1,
    items: [
      { id: 1, productId: 101, quantity: 1, unitPrice: 150000 },
      { id: 2, productId: 102, quantity: 1, unitPrice: 350000 }
    ],
    updatedAt: now
  }
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 1,
    orderCode: 'BEE-ORDER-0001',
    userId: 1,
    items: [
      {
        id: 1,
        productId: 101,
        productName: 'Khay Cắm Bút Gỗ Sồi',
        quantity: 1,
        unitPrice: 150000
      },
      {
        id: 2,
        productId: 102,
        productName: 'Đèn Bàn Pixar',
        quantity: 1,
        unitPrice: 350000
      }
    ],
    subtotal: 500000,
    shippingFee: 30000,
    totalAmount: 530000,
    status: 'shipping',
    createdAt: now
  }
];
